### PR TITLE
RootShell: use jitpack dependency instead of aar file

### PR DESCRIPTION
**Pull request by juanitobananas**
Using jitpack.io might solve #84. It will hopefully be able to know that it has to download 1.6 and not 5.0,  though I am not sure.

### CODE REVIEW

**Comment by JcChimjj** [comment]
#87

**Comment by JcChimjj** [comment]
#87

**Comment by JcChimjj** [comment]
#87

**Comment by Stericson** [comment]
@JcChimjj @juanitobananas Is this still a WIP? Any confirmation of whether proper version is fetched?

**Comment by Stericson** [comment]
Sounds good to me. Thanks :+1: Use to using Gitlab which won't let you merge a MR marked as WIP.

**Comment by juanitobananas** [comment]
No problem! :+1:

**Pull request merged**
