### PR TITLE
Android studio version

### PR DESCRIPTION
**Pull request by odemolliens**
Migrated to Android studio version.

Include TRAVIS file

Maybe we can add a jitpack.io on this repo

### CODE REVIEW

**Comment by Stericson** [comment]
@odemolliens Can you remove the project specific file *.iml from this commit?

**Comment by odemolliens** [comment]
sure ! done in last commit

**Comment by Stericson** [comment]
Thanks!

**Comment by Bladfool** [comment]
> Migrated to Android studio version.
> 
> Include TRAVIS file
> 
> Maybe we can add a jitpack.io on this repo
>

**Review by Bladfool — APPROVED** [review]

**Pull request merged**
